name: Java CI with Gradle

on: [pull_request, workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.10.2

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: collectArtifacts

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            artifacts
